/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import Controle.ConexaoBD;
import Controle.ControleAluno;
import model.ModeloAluno;

/**
 *
 * @author Peter
 */
public class FichaCadastroAluno extends javax.swing.JFrame {
    ModeloAluno modaluno = new ModeloAluno();
    ConexaoBD conex = new ConexaoBD();
    ControleAluno control = new ControleAluno();
    /**
     * Creates new form FichaCadastroAluno
     */
    public FichaCadastroAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CelAluno = new javax.swing.JFormattedTextField();
        try{
            javax.swing.text.MaskFormatter celular = new javax.swing.text.MaskFormatter("(##)####-####");

            CelAluno = new javax.swing.JFormattedTextField(celular);
        }catch(Exception e){
        }
        jLabelCadastroAluno = new javax.swing.JLabel();
        jLabelNomeAluno = new javax.swing.JLabel();
        jLabelEnderecoAluno = new javax.swing.JLabel();
        jLabelCidadeAluno = new javax.swing.JLabel();
        jLabelCPFAluno = new javax.swing.JLabel();
        jLabelBairroAluno = new javax.swing.JLabel();
        jLabelTelefoneAluno = new javax.swing.JLabel();
        jLabelCelularAluno = new javax.swing.JLabel();
        jLabelTurnoAluno = new javax.swing.JLabel();
        jLabelSexoAluno = new javax.swing.JLabel();
        jButtonSalvarAluno = new javax.swing.JButton();
        jButtonCancelarAluno = new javax.swing.JButton();
        CpfAluno = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter cpf = new javax.swing.text.MaskFormatter("###.###.###-##");

            CpfAluno = new javax.swing.JFormattedTextField(cpf);
        }catch(Exception e){
        }
        NomeAluno = new javax.swing.JTextField();
        SexoAluno = new javax.swing.JTextField();
        EndAluno = new javax.swing.JTextField();
        CidAluno = new javax.swing.JTextField();
        BairroAluno = new javax.swing.JTextField();
        TelAluno = new javax.swing.JFormattedTextField();
        try{
            javax.swing.text.MaskFormatter telefone = new javax.swing.text.MaskFormatter("(##)####-####");

            TelAluno = new javax.swing.JFormattedTextField(telefone);
        }catch(Exception e){
        }
        turno = new javax.swing.JComboBox();
        CELAluno = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter celular = new javax.swing.text.MaskFormatter("(##)####-####");

            CELAluno = new javax.swing.JFormattedTextField(celular);
        }catch(Exception e){
        }
        DatMatricula = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter data = new javax.swing.text.MaskFormatter("##/##/####");

            DatMatricula = new javax.swing.JFormattedTextField(data);
        }catch(Exception e){
        }
        jLabel1 = new javax.swing.JLabel();

        CelAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CelAlunoActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabelCadastroAluno.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabelCadastroAluno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCadastroAluno.setText("Cadastro de Aluno");

        jLabelNomeAluno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelNomeAluno.setText("Nome: ");

        jLabelEnderecoAluno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelEnderecoAluno.setText("Endereço:");

        jLabelCidadeAluno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCidadeAluno.setText("Cidade: ");

        jLabelCPFAluno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCPFAluno.setText("CPF:");

        jLabelBairroAluno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelBairroAluno.setText("Bairro:");

        jLabelTelefoneAluno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTelefoneAluno.setText("Telefone:");

        jLabelCelularAluno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCelularAluno.setText("Celular:");

        jLabelTurnoAluno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTurnoAluno.setText("Turno:");

        jLabelSexoAluno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelSexoAluno.setText("Sexo:");

        jButtonSalvarAluno.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonSalvarAluno.setText("Salvar");
        jButtonSalvarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarAlunoActionPerformed(evt);
            }
        });

        jButtonCancelarAluno.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonCancelarAluno.setText("Cancelar");
        jButtonCancelarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarAlunoActionPerformed(evt);
            }
        });

        CpfAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CpfAlunoActionPerformed(evt);
            }
        });

        NomeAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeAlunoActionPerformed(evt);
            }
        });

        SexoAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SexoAlunoActionPerformed(evt);
            }
        });

        EndAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EndAlunoActionPerformed(evt);
            }
        });

        CidAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CidAlunoActionPerformed(evt);
            }
        });

        BairroAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BairroAlunoActionPerformed(evt);
            }
        });

        turno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Manhã", "Tarde", "Noite" }));

        DatMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatMatriculaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Data Matricula");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTurnoAluno)
                            .addComponent(jLabelEnderecoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCidadeAluno)
                            .addComponent(jLabelSexoAluno)
                            .addComponent(jLabelTelefoneAluno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(EndAluno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(SexoAluno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(CidAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabelBairroAluno)))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 94, Short.MAX_VALUE)
                                        .addComponent(jButtonSalvarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(jButtonCancelarAluno)
                                        .addGap(28, 28, 28))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(TelAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelCelularAluno)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BairroAluno, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                    .addComponent(CELAluno)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(turno, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(NomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelCPFAluno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CpfAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(DatMatricula)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelCadastroAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelCadastroAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNomeAluno)
                    .addComponent(DatMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CpfAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCPFAluno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SexoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSexoAluno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CidAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCidadeAluno)
                    .addComponent(jLabelBairroAluno)
                    .addComponent(BairroAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EndAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEnderecoAluno))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSalvarAluno)
                            .addComponent(jButtonCancelarAluno))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TelAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTelefoneAluno)
                            .addComponent(jLabelCelularAluno)
                            .addComponent(CELAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTurnoAluno)
                            .addComponent(turno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(78, Short.MAX_VALUE))))
        );

        setSize(new java.awt.Dimension(566, 388));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CpfAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CpfAlunoActionPerformed

    }//GEN-LAST:event_CpfAlunoActionPerformed

    private void NomeAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeAlunoActionPerformed

    private void SexoAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SexoAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SexoAlunoActionPerformed

    private void EndAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EndAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EndAlunoActionPerformed

    private void CidAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CidAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CidAlunoActionPerformed

    private void BairroAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BairroAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BairroAlunoActionPerformed

    private void CelAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CelAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CelAlunoActionPerformed

    private void jButtonSalvarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarAlunoActionPerformed
        modaluno.setNome(NomeAluno.getText());
        modaluno.setData_Matricula(DatMatricula.getText());
        modaluno.setCPF(CpfAluno.getText());
        modaluno.setSexo(SexoAluno.getText());
        modaluno.setCidade(CidAluno.getText());
        modaluno.setBairro(BairroAluno.getText());
        modaluno.setEndereco(EndAluno.getText());
        modaluno.setTelefone(TelAluno.getText());
        modaluno.setCelular(CELAluno.getText());
        modaluno.setTurno((String) turno.getSelectedItem());
        control.salvar(modaluno);
        dispose();
        
    }//GEN-LAST:event_jButtonSalvarAlunoActionPerformed

    private void jButtonCancelarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarAlunoActionPerformed
        FichaCadastroAluno.this.dispose();
    }//GEN-LAST:event_jButtonCancelarAlunoActionPerformed

    private void DatMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DatMatriculaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FichaCadastroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FichaCadastroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FichaCadastroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FichaCadastroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FichaCadastroAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BairroAluno;
    private javax.swing.JTextField CELAluno;
    private javax.swing.JFormattedTextField CelAluno;
    private javax.swing.JTextField CidAluno;
    private javax.swing.JTextField CpfAluno;
    private javax.swing.JTextField DatMatricula;
    private javax.swing.JTextField EndAluno;
    private javax.swing.JTextField NomeAluno;
    private javax.swing.JTextField SexoAluno;
    private javax.swing.JFormattedTextField TelAluno;
    private javax.swing.JButton jButtonCancelarAluno;
    private javax.swing.JButton jButtonSalvarAluno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBairroAluno;
    private javax.swing.JLabel jLabelCPFAluno;
    private javax.swing.JLabel jLabelCadastroAluno;
    private javax.swing.JLabel jLabelCelularAluno;
    private javax.swing.JLabel jLabelCidadeAluno;
    private javax.swing.JLabel jLabelEnderecoAluno;
    private javax.swing.JLabel jLabelNomeAluno;
    private javax.swing.JLabel jLabelSexoAluno;
    private javax.swing.JLabel jLabelTelefoneAluno;
    private javax.swing.JLabel jLabelTurnoAluno;
    private javax.swing.JComboBox turno;
    // End of variables declaration//GEN-END:variables
}
