/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import javax.swing.JOptionPane;
import modeloDao.DaoProfessor;
import modeloBeans.BeansProfessor;
import modeloConnection.ConexaoBD;



/**
 *
 * @author Peter
 */
public class FichaCadastroProfessor extends javax.swing.JFrame {
    BeansProfessor modprof = new BeansProfessor();
    DaoProfessor controlprof = new DaoProfessor();
    ConexaoBD conex = new ConexaoBD();
    int flag =0;

    /**
     * Creates new form FichaCadastroProfessor
     */
    public FichaCadastroProfessor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSexoProfessor = new javax.swing.JLabel();
        BairroProfessor = new javax.swing.JTextField();
        jButtonSalvarProfessor = new javax.swing.JButton();
        jButtonCancelarProfessor = new javax.swing.JButton();
        jLabelNomeProfessor = new javax.swing.JLabel();
        CelProfessor = new javax.swing.JFormattedTextField();
        try{
            javax.swing.text.MaskFormatter celular = new javax.swing.text.MaskFormatter("(##)####-####");

            CelProfessor = new javax.swing.JFormattedTextField(celular);
        }catch(Exception e){
        }
        jLabelEnderecoProfessor = new javax.swing.JLabel();
        NomeProfessor = new javax.swing.JTextField();
        TelProfessor = new javax.swing.JFormattedTextField();
        try{
            javax.swing.text.MaskFormatter tel = new javax.swing.text.MaskFormatter("(##)####-####");

            TelProfessor = new javax.swing.JFormattedTextField(tel);
        }catch(Exception e){
        }
        jLabelCidadeProfessor = new javax.swing.JLabel();
        SexoProfessor = new javax.swing.JTextField();
        jLabelCPFProfessor = new javax.swing.JLabel();
        jLabelBairroProfessor = new javax.swing.JLabel();
        EndProfessor = new javax.swing.JTextField();
        jLabelCadastroProfessor = new javax.swing.JLabel();
        jLabelTelefoneProfessor = new javax.swing.JLabel();
        jLabelCelularProfessor = new javax.swing.JLabel();
        CidadeProfessor = new javax.swing.JTextField();
        jLabelTurnoProfessor = new javax.swing.JLabel();
        TurnoProfessor = new javax.swing.JComboBox();
        CpfProfessor = new javax.swing.JFormattedTextField();
        try{
            javax.swing.text.MaskFormatter cpf = new javax.swing.text.MaskFormatter("###.###.###-##");

            CpfProfessor = new javax.swing.JFormattedTextField(cpf);
        }catch(Exception e){
        }
        jButtonExcluirprof = new javax.swing.JButton();
        jButtonPesquisarprof = new javax.swing.JButton();
        jTextFieldpesquisaprofessor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProfessor = new javax.swing.JTable();
        jButtonNovoprof = new javax.swing.JButton();
        jButtonEditarProfessor = new javax.swing.JButton();
        jLabelIDprofessor = new javax.swing.JLabel();
        jTextFieldIDprofessor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(875, 518));
        setResizable(false);

        jLabelSexoProfessor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelSexoProfessor.setText("Sexo:");

        BairroProfessor.setEnabled(false);
        BairroProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BairroProfessorActionPerformed(evt);
            }
        });

        jButtonSalvarProfessor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonSalvarProfessor.setText("Salvar");
        jButtonSalvarProfessor.setEnabled(false);
        jButtonSalvarProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarProfessorActionPerformed(evt);
            }
        });

        jButtonCancelarProfessor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonCancelarProfessor.setText("Cancelar");
        jButtonCancelarProfessor.setEnabled(false);
        jButtonCancelarProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarProfessorActionPerformed(evt);
            }
        });

        jLabelNomeProfessor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelNomeProfessor.setText("Nome:");

        CelProfessor.setEnabled(false);
        CelProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CelProfessorActionPerformed(evt);
            }
        });

        jLabelEnderecoProfessor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelEnderecoProfessor.setText("Endereço:");

        NomeProfessor.setEnabled(false);
        NomeProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeProfessorActionPerformed(evt);
            }
        });

        TelProfessor.setEnabled(false);

        jLabelCidadeProfessor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelCidadeProfessor.setText("Cidade: ");

        SexoProfessor.setEnabled(false);
        SexoProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SexoProfessorActionPerformed(evt);
            }
        });

        jLabelCPFProfessor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelCPFProfessor.setText("CPF:");

        jLabelBairroProfessor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelBairroProfessor.setText("Bairro:");

        EndProfessor.setEnabled(false);
        EndProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EndProfessorActionPerformed(evt);
            }
        });

        jLabelCadastroProfessor.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabelCadastroProfessor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCadastroProfessor.setText("Cadastro de Professor");

        jLabelTelefoneProfessor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelTelefoneProfessor.setText("Telefone:");

        jLabelCelularProfessor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelCelularProfessor.setText("Celular:");

        CidadeProfessor.setEnabled(false);
        CidadeProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CidadeProfessorActionPerformed(evt);
            }
        });

        jLabelTurnoProfessor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelTurnoProfessor.setText("Turno:");

        TurnoProfessor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Manhã", "Tarde", "Noite" }));
        TurnoProfessor.setEnabled(false);
        TurnoProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TurnoProfessorActionPerformed(evt);
            }
        });

        CpfProfessor.setEnabled(false);
        CpfProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CpfProfessorActionPerformed(evt);
            }
        });

        jButtonExcluirprof.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonExcluirprof.setText("Excluir");
        jButtonExcluirprof.setEnabled(false);
        jButtonExcluirprof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirprofActionPerformed(evt);
            }
        });

        jButtonPesquisarprof.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonPesquisarprof.setText("Pesquisar");
        jButtonPesquisarprof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarprofActionPerformed(evt);
            }
        });

        jTextFieldpesquisaprofessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldpesquisaprofessorActionPerformed(evt);
            }
        });

        jTableProfessor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTableProfessor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableProfessor);

        jButtonNovoprof.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonNovoprof.setText("Novo");
        jButtonNovoprof.setMaximumSize(new java.awt.Dimension(67, 23));
        jButtonNovoprof.setPreferredSize(new java.awt.Dimension(83, 23));
        jButtonNovoprof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoprofActionPerformed(evt);
            }
        });

        jButtonEditarProfessor.setText("Editar");
        jButtonEditarProfessor.setEnabled(false);
        jButtonEditarProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarProfessorActionPerformed(evt);
            }
        });

        jLabelIDprofessor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelIDprofessor.setText("ID:");

        jTextFieldIDprofessor.setEnabled(false);
        jTextFieldIDprofessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDprofessorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addComponent(jLabelCadastroProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonExcluirprof, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCancelarProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(jButtonSalvarProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNovoprof, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEditarProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCidadeProfessor)
                                    .addComponent(jLabelSexoProfessor)
                                    .addComponent(jLabelCPFProfessor)
                                    .addComponent(jLabelIDprofessor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelNomeProfessor))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(CpfProfessor)
                                        .addComponent(SexoProfessor, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(CidadeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(NomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldIDprofessor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldpesquisaprofessor, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonPesquisarprof)))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCelularProfessor)
                            .addComponent(jLabelTurnoProfessor)
                            .addComponent(jLabelTelefoneProfessor)
                            .addComponent(jLabelBairroProfessor)
                            .addComponent(jLabelEnderecoProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TurnoProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EndProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(BairroProfessor)
                            .addComponent(TelProfessor)
                            .addComponent(CelProfessor))))
                .addGap(113, 113, 113))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCadastroProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIDprofessor)
                    .addComponent(jTextFieldIDprofessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(EndProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelEnderecoProfessor))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BairroProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(NomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelNomeProfessor))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(CpfProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelCPFProfessor))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(SexoProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(CidadeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelBairroProfessor)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelSexoProfessor)
                                        .addComponent(jLabelTelefoneProfessor)
                                        .addComponent(TelProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelCidadeProfessor)
                                        .addComponent(CelProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelCelularProfessor))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonNovoprof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSalvarProfessor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancelarProfessor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonExcluirprof)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEditarProfessor)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTurnoProfessor)
                    .addComponent(TurnoProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldpesquisaprofessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisarprof))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(891, 488));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BairroProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BairroProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BairroProfessorActionPerformed

    private void jButtonSalvarProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarProfessorActionPerformed
        if(flag==1){
        modprof.setNome(NomeProfessor.getText());
        modprof.setCPF(CpfProfessor.getText());
        modprof.setSexo(SexoProfessor.getText());
        modprof.setCidade(CidadeProfessor.getText());
        modprof.setBairro(BairroProfessor.getText());
        modprof.setEndereco(EndProfessor.getText());
        modprof.setTelefone(TelProfessor.getText());
        modprof.setCelular(CelProfessor.getText());
        modprof.setTurno((String)TurnoProfessor.getSelectedItem());
        controlprof.salvar(modprof);
        dispose();
        }else{
            modprof.setCodigo(Integer.parseInt(jTextFieldIDprofessor.getText()));
            modprof.setNome(NomeProfessor.getText());
            modprof.setCPF(CpfProfessor.getText());
            modprof.setSexo(SexoProfessor.getText());
            modprof.setCidade(CidadeProfessor.getText());
            modprof.setEndereco(EndProfessor.getText());
            modprof.setBairro(BairroProfessor.getText());
            modprof.setTelefone(TelProfessor.getText());
            modprof.setCelular(CelProfessor.getText());
            modprof.setTurno((String)TurnoProfessor.getSelectedItem());
            controlprof.EditarProfessor(modprof);
            jButtonSalvarProfessor.setEnabled(false);
            jButtonCancelarProfessor.setEnabled(false);
            jButtonNovoprof.setEnabled(true);
            NomeProfessor.setEnabled(!true);
            CpfProfessor.setEnabled(!true);
            SexoProfessor.setEnabled(!true);
            CidadeProfessor.setEnabled(!true);
            EndProfessor.setEnabled(!true);
            BairroProfessor.setEnabled(!true);
            TelProfessor.setEnabled(!true);
            CelProfessor.setEnabled(!true);
            TurnoProfessor.setEnabled(false);
            jTextFieldpesquisaprofessor.setText("");
            NomeProfessor.setText("");
            CpfProfessor.setText("");
            SexoProfessor.setText("");
            CidadeProfessor.setText("");
            EndProfessor.setText("");
            BairroProfessor.setText("");
            TelProfessor.setText("");
            CelProfessor.setText("");
        }
        
    }//GEN-LAST:event_jButtonSalvarProfessorActionPerformed

    private void CelProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CelProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CelProfessorActionPerformed

    private void NomeProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeProfessorActionPerformed

    private void SexoProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SexoProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SexoProfessorActionPerformed

    private void EndProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EndProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EndProfessorActionPerformed

    private void CidadeProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CidadeProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CidadeProfessorActionPerformed

    private void jButtonCancelarProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarProfessorActionPerformed
        NomeProfessor.setEnabled(!true);
        CpfProfessor.setEnabled(!true);
        SexoProfessor.setEnabled(!true);
        CidadeProfessor.setEnabled(!true);
        EndProfessor.setEnabled(!true);
        BairroProfessor.setEnabled(!true);
        TelProfessor.setEnabled(!true);
        CelProfessor.setEnabled(!true);
        jButtonSalvarProfessor.setEnabled(!true);
        jButtonCancelarProfessor.setEnabled(!true);
        TurnoProfessor.setEnabled(!true);
        jButtonNovoprof.setEnabled(true);
        jButtonEditarProfessor.setEnabled(false);
        NomeProfessor.setText("");
        CpfProfessor.setText("");
        SexoProfessor.setText("");
        CidadeProfessor.setText("");
        EndProfessor.setText("");
        BairroProfessor.setText("");
        TelProfessor.setText("");
        CelProfessor.setText("");
        
    }//GEN-LAST:event_jButtonCancelarProfessorActionPerformed

    private void CpfProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CpfProfessorActionPerformed
      
    }//GEN-LAST:event_CpfProfessorActionPerformed

    private void TurnoProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TurnoProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TurnoProfessorActionPerformed

    private void jButtonPesquisarprofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarprofActionPerformed
        modprof.setPesquisa(jTextFieldpesquisaprofessor.getText());
        BeansProfessor modeloProfessor = controlprof.buscaProfessor(modprof);
        jTextFieldIDprofessor.setText(String.valueOf(modeloProfessor.getCodigo()));
        NomeProfessor.setText(modeloProfessor.getNome());
        CpfProfessor.setText(modeloProfessor.getCPF());
        SexoProfessor.setText(modeloProfessor.getSexo());
        CidadeProfessor.setText(modeloProfessor.getCidade());
        BairroProfessor.setText(modeloProfessor.getBairro());
        EndProfessor.setText(modeloProfessor.getEndereco());
        TelProfessor.setText(modeloProfessor.getTelefone());
        CelProfessor.setText(modeloProfessor.getCelular());
        TurnoProfessor.setSelectedItem(modeloProfessor.getTurno());
        jTableProfessor.setEnabled(true);
        jButtonEditarProfessor.setEnabled(true);
        jButtonSalvarProfessor.setEnabled(false);
        jButtonNovoprof.setEnabled(false);
        jButtonExcluirprof.setEnabled(true);
        
        
    }//GEN-LAST:event_jButtonPesquisarprofActionPerformed

    private void jTextFieldpesquisaprofessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldpesquisaprofessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldpesquisaprofessorActionPerformed

    private void jButtonNovoprofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoprofActionPerformed
        flag =1;
        NomeProfessor.setEnabled(true);
        CpfProfessor.setEnabled(true);
        SexoProfessor.setEnabled(true);
        CidadeProfessor.setEnabled(true);
        EndProfessor.setEnabled(true);
        BairroProfessor.setEnabled(true);
        TelProfessor.setEnabled(true);
        CelProfessor.setEnabled(true);
        jButtonSalvarProfessor.setEnabled(true);
        jButtonCancelarProfessor.setEnabled(true);
        TurnoProfessor.setEnabled(true);
    }//GEN-LAST:event_jButtonNovoprofActionPerformed

    private void jButtonEditarProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarProfessorActionPerformed
        flag =2;
        NomeProfessor.setEnabled(true);
        CpfProfessor.setEnabled(true);
        SexoProfessor.setEnabled(true);
        CidadeProfessor.setEnabled(true);
        EndProfessor.setEnabled(true);
        BairroProfessor.setEnabled(true);
        TelProfessor.setEnabled(true);
        CelProfessor.setEnabled(true);
        TurnoProfessor.setEnabled(true);
        jButtonSalvarProfessor.setEnabled(true);
        jButtonCancelarProfessor.setEnabled(true);
        jButtonEditarProfessor.setEnabled(false);
        jButtonExcluirprof.setEnabled(false);
        jButtonNovoprof.setEnabled(false);
    }//GEN-LAST:event_jButtonEditarProfessorActionPerformed

    private void jButtonExcluirprofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirprofActionPerformed
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja Realmente Efetuar Exclusão? ");
        if(resposta==JOptionPane.YES_OPTION){
            modprof.setCodigo(Integer.parseInt(jTextFieldIDprofessor.getText()));
            controlprof.ExcluirProfessor(modprof);
            NomeProfessor.setText("");
            CpfProfessor.setText("");
            SexoProfessor.setText("");
            CidadeProfessor.setText("");
            EndProfessor.setText("");
            BairroProfessor.setText("");
            TelProfessor.setText("");
            CelProfessor.setText("");
            jTextFieldIDprofessor.setText("");
            jTextFieldpesquisaprofessor.setText("");
            jButtonEditarProfessor.setEnabled(false);
            jButtonExcluirprof.setEnabled(false);
            jButtonNovoprof.setEnabled(true);
        }
    }//GEN-LAST:event_jButtonExcluirprofActionPerformed

    private void jTextFieldIDprofessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDprofessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDprofessorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FichaCadastroProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FichaCadastroProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FichaCadastroProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FichaCadastroProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FichaCadastroProfessor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BairroProfessor;
    private javax.swing.JFormattedTextField CelProfessor;
    private javax.swing.JTextField CidadeProfessor;
    private javax.swing.JFormattedTextField CpfProfessor;
    private javax.swing.JTextField EndProfessor;
    private javax.swing.JTextField NomeProfessor;
    private javax.swing.JTextField SexoProfessor;
    private javax.swing.JFormattedTextField TelProfessor;
    private javax.swing.JComboBox TurnoProfessor;
    private javax.swing.JButton jButtonCancelarProfessor;
    private javax.swing.JButton jButtonEditarProfessor;
    private javax.swing.JButton jButtonExcluirprof;
    private javax.swing.JButton jButtonNovoprof;
    private javax.swing.JButton jButtonPesquisarprof;
    private javax.swing.JButton jButtonSalvarProfessor;
    private javax.swing.JLabel jLabelBairroProfessor;
    private javax.swing.JLabel jLabelCPFProfessor;
    private javax.swing.JLabel jLabelCadastroProfessor;
    private javax.swing.JLabel jLabelCelularProfessor;
    private javax.swing.JLabel jLabelCidadeProfessor;
    private javax.swing.JLabel jLabelEnderecoProfessor;
    private javax.swing.JLabel jLabelIDprofessor;
    private javax.swing.JLabel jLabelNomeProfessor;
    private javax.swing.JLabel jLabelSexoProfessor;
    private javax.swing.JLabel jLabelTelefoneProfessor;
    private javax.swing.JLabel jLabelTurnoProfessor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProfessor;
    private javax.swing.JTextField jTextFieldIDprofessor;
    private javax.swing.JTextField jTextFieldpesquisaprofessor;
    // End of variables declaration//GEN-END:variables
}
