/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author Peter
 */
public class FichaCadastroProfessor extends javax.swing.JFrame {

    /**
     * Creates new form FichaCadastroProfessor
     */
    public FichaCadastroProfessor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NomeAluno6 = new javax.swing.JTextField();
        jLabelSexoProfessor = new javax.swing.JLabel();
        NomeAluno7 = new javax.swing.JTextField();
        jButtonSalvarProfessor = new javax.swing.JButton();
        jButtonCancelarProfessor = new javax.swing.JButton();
        jLabelNomeProfessor = new javax.swing.JLabel();
        NomeAluno = new javax.swing.JTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabelEnderecoProfessor = new javax.swing.JLabel();
        NomeAluno1 = new javax.swing.JTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jLabelCidadeProfessor = new javax.swing.JLabel();
        NomeAluno2 = new javax.swing.JTextField();
        jLabelCPFProfessor = new javax.swing.JLabel();
        jLabelBairroProfessor = new javax.swing.JLabel();
        NomeAluno4 = new javax.swing.JTextField();
        jLabelCadastroProfessor = new javax.swing.JLabel();
        jLabelTelefoneProfessor = new javax.swing.JLabel();
        jLabelCelularProfessor = new javax.swing.JLabel();
        NomeAluno5 = new javax.swing.JTextField();
        jLabelTurnoProfessor = new javax.swing.JLabel();
        jLabelCREFProfessor = new javax.swing.JLabel();
        NomeAluno8 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        NomeAluno6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeAluno6ActionPerformed(evt);
            }
        });

        jLabelSexoProfessor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelSexoProfessor.setText("Sexo:");

        NomeAluno7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeAluno7ActionPerformed(evt);
            }
        });

        jButtonSalvarProfessor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonSalvarProfessor.setText("Salvar");
        jButtonSalvarProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarProfessorActionPerformed(evt);
            }
        });

        jButtonCancelarProfessor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonCancelarProfessor.setText("Cancelar");
        jButtonCancelarProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarProfessorActionPerformed(evt);
            }
        });

        jLabelNomeProfessor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelNomeProfessor.setText("Nome: ");

        NomeAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeAlunoActionPerformed(evt);
            }
        });

        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });

        jLabelEnderecoProfessor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelEnderecoProfessor.setText("Endereço:");

        NomeAluno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeAluno1ActionPerformed(evt);
            }
        });

        jLabelCidadeProfessor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCidadeProfessor.setText("Cidade: ");

        NomeAluno2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeAluno2ActionPerformed(evt);
            }
        });

        jLabelCPFProfessor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCPFProfessor.setText("CPF:");

        jLabelBairroProfessor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelBairroProfessor.setText("Bairro:");

        NomeAluno4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeAluno4ActionPerformed(evt);
            }
        });

        jLabelCadastroProfessor.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabelCadastroProfessor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCadastroProfessor.setText("Cadastro de Professor");

        jLabelTelefoneProfessor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTelefoneProfessor.setText("Telefone:");

        jLabelCelularProfessor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCelularProfessor.setText("Celular:");

        NomeAluno5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeAluno5ActionPerformed(evt);
            }
        });

        jLabelTurnoProfessor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTurnoProfessor.setText("Turno:");

        jLabelCREFProfessor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCREFProfessor.setText("CREF:");

        NomeAluno8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeAluno8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTurnoProfessor)
                            .addComponent(jLabelEnderecoProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCidadeProfessor)
                            .addComponent(jLabelSexoProfessor)
                            .addComponent(jLabelTelefoneProfessor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NomeAluno6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelCREFProfessor))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelCelularProfessor))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(NomeAluno4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NomeAluno2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(NomeAluno5, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelBairroProfessor)))
                                .addGap(0, 1, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonSalvarProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jButtonCancelarProfessor)
                                .addGap(28, 28, 28)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jFormattedTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(NomeAluno7, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(NomeAluno8))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(NomeAluno1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelCPFProfessor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(NomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelCadastroProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelCadastroProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeAluno1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNomeProfessor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCPFProfessor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeAluno2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSexoProfessor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeAluno5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCidadeProfessor)
                    .addComponent(jLabelBairroProfessor)
                    .addComponent(NomeAluno7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeAluno4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEnderecoProfessor))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelCelularProfessor))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabelTelefoneProfessor))
                    .addComponent(jFormattedTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeAluno8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCREFProfessor)
                    .addComponent(NomeAluno6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTurnoProfessor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvarProfessor)
                    .addComponent(jButtonCancelarProfessor))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(566, 388));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NomeAluno6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeAluno6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeAluno6ActionPerformed

    private void NomeAluno7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeAluno7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeAluno7ActionPerformed

    private void jButtonSalvarProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalvarProfessorActionPerformed

    private void NomeAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeAlunoActionPerformed

    }//GEN-LAST:event_NomeAlunoActionPerformed

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void NomeAluno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeAluno1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeAluno1ActionPerformed

    private void NomeAluno2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeAluno2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeAluno2ActionPerformed

    private void NomeAluno4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeAluno4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeAluno4ActionPerformed

    private void NomeAluno5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeAluno5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeAluno5ActionPerformed

    private void jButtonCancelarProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarProfessorActionPerformed
        FichaCadastroProfessor.this.dispose();
    }//GEN-LAST:event_jButtonCancelarProfessorActionPerformed

    private void NomeAluno8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeAluno8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeAluno8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FichaCadastroProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FichaCadastroProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FichaCadastroProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FichaCadastroProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FichaCadastroProfessor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NomeAluno;
    private javax.swing.JTextField NomeAluno1;
    private javax.swing.JTextField NomeAluno2;
    private javax.swing.JTextField NomeAluno4;
    private javax.swing.JTextField NomeAluno5;
    private javax.swing.JTextField NomeAluno6;
    private javax.swing.JTextField NomeAluno7;
    private javax.swing.JTextField NomeAluno8;
    private javax.swing.JButton jButtonCancelarProfessor;
    private javax.swing.JButton jButtonSalvarProfessor;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabelBairroProfessor;
    private javax.swing.JLabel jLabelCPFProfessor;
    private javax.swing.JLabel jLabelCREFProfessor;
    private javax.swing.JLabel jLabelCadastroProfessor;
    private javax.swing.JLabel jLabelCelularProfessor;
    private javax.swing.JLabel jLabelCidadeProfessor;
    private javax.swing.JLabel jLabelEnderecoProfessor;
    private javax.swing.JLabel jLabelNomeProfessor;
    private javax.swing.JLabel jLabelSexoProfessor;
    private javax.swing.JLabel jLabelTelefoneProfessor;
    private javax.swing.JLabel jLabelTurnoProfessor;
    // End of variables declaration//GEN-END:variables
}
