/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author Peter
 */
public class FichaCadastroEquipamento extends javax.swing.JFrame {

    /**
     * Creates new form FichaCadastroEquipamento
     */
    public FichaCadastroEquipamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSalvarEquipamento = new javax.swing.JButton();
        jButtonCancelarEquipamento = new javax.swing.JButton();
        jLabelNomeEquipamento = new javax.swing.JLabel();
        jLabelCadastroEquipamento = new javax.swing.JLabel();
        NomeAluno1 = new javax.swing.JTextField();
        jLabelSerialEquipamento = new javax.swing.JLabel();
        NomeAluno2 = new javax.swing.JTextField();
        jLabelDescriçãoEquipamento = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DescApa = new javax.swing.JTextArea();
        Local = new javax.swing.JTextField();
        jLabelValorEquipamento = new javax.swing.JLabel();
        GarantiaEquipamento = new javax.swing.JLabel();
        jLabelLocalEquipamento = new javax.swing.JLabel();
        jtGaranto = new javax.swing.JTextField();
        Valorapa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jButtonSalvarEquipamento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonSalvarEquipamento.setText("Salvar");
        jButtonSalvarEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarEquipamentoActionPerformed(evt);
            }
        });

        jButtonCancelarEquipamento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonCancelarEquipamento.setText("Cancelar");
        jButtonCancelarEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarEquipamentoActionPerformed(evt);
            }
        });

        jLabelNomeEquipamento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelNomeEquipamento.setText("Nome: ");

        jLabelCadastroEquipamento.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabelCadastroEquipamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCadastroEquipamento.setText("Cadastro de Equipamentos");

        NomeAluno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeAluno1ActionPerformed(evt);
            }
        });

        jLabelSerialEquipamento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelSerialEquipamento.setText("Nº Serial:");

        NomeAluno2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeAluno2ActionPerformed(evt);
            }
        });

        jLabelDescriçãoEquipamento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelDescriçãoEquipamento.setText("Descrição:");

        DescApa.setColumns(20);
        DescApa.setRows(5);
        jScrollPane1.setViewportView(DescApa);

        jLabelValorEquipamento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelValorEquipamento.setText("Valor Pago");

        GarantiaEquipamento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        GarantiaEquipamento.setText("Garantia");

        jLabelLocalEquipamento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelLocalEquipamento.setText("Local Atual");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelNomeEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(NomeAluno1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabelSerialEquipamento)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(NomeAluno2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelDescriçãoEquipamento)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane1))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButtonSalvarEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32)
                            .addComponent(jButtonCancelarEquipamento)
                            .addGap(148, 148, 148)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabelLocalEquipamento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Local))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabelValorEquipamento)
                                .addGap(10, 10, 10)
                                .addComponent(Valorapa)))
                        .addGap(18, 18, 18)
                        .addComponent(GarantiaEquipamento)
                        .addGap(18, 18, 18)
                        .addComponent(jtGaranto, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelCadastroEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelCadastroEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeAluno1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNomeEquipamento)
                    .addComponent(jLabelSerialEquipamento)
                    .addComponent(NomeAluno2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabelDescriçãoEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelValorEquipamento)
                    .addComponent(Valorapa, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GarantiaEquipamento)
                    .addComponent(jtGaranto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLocalEquipamento)
                    .addComponent(Local, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvarEquipamento)
                    .addComponent(jButtonCancelarEquipamento))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(566, 388));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarEquipamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalvarEquipamentoActionPerformed

    private void jButtonCancelarEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarEquipamentoActionPerformed
        FichaCadastroEquipamento.this.dispose();
    }//GEN-LAST:event_jButtonCancelarEquipamentoActionPerformed

    private void NomeAluno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeAluno1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeAluno1ActionPerformed

    private void NomeAluno2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeAluno2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeAluno2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FichaCadastroEquipamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FichaCadastroEquipamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FichaCadastroEquipamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FichaCadastroEquipamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FichaCadastroEquipamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea DescApa;
    private javax.swing.JLabel GarantiaEquipamento;
    private javax.swing.JTextField Local;
    private javax.swing.JTextField NomeAluno1;
    private javax.swing.JTextField NomeAluno2;
    private javax.swing.JTextField Valorapa;
    private javax.swing.JButton jButtonCancelarEquipamento;
    private javax.swing.JButton jButtonSalvarEquipamento;
    private javax.swing.JLabel jLabelCadastroEquipamento;
    private javax.swing.JLabel jLabelDescriçãoEquipamento;
    private javax.swing.JLabel jLabelLocalEquipamento;
    private javax.swing.JLabel jLabelNomeEquipamento;
    private javax.swing.JLabel jLabelSerialEquipamento;
    private javax.swing.JLabel jLabelValorEquipamento;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtGaranto;
    // End of variables declaration//GEN-END:variables
}
